lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Drew Kuerzi's Senior Project Proposal]
description: [This site describes the features of my project along with similar applications and their features.]
github:
  zip_url: https://hanover-cs.github.io/HC23-Drew-Kuerzi-Senior-Project/
  another_url: Drew_Kuerzi/